name: Build and deploy .NET Core 3.1 project to Azure Function App - paymentsystemfunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # De rootmap van je project
  DOTNET_VERSION: '3.1.x'  # Specificeer de juiste .NET versie (3.1.x voor .NET Core 3.1)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Dit is vereist voor het aanvragen van de JWT

    steps:
      # Stap 1: Checkout je repository
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      # Stap 2: Setup de juiste .NET SDK versie (3.1)
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Stap 3: Installeer de benodigde Microsoft.NET.Sdk.Functions
      - name: Install Microsoft.NET.Sdk.Functions
        run: |
          dotnet new --install Microsoft.NET.Sdk.Functions::3.0.11

      # Stap 4: Bouw het project
      - name: Resolve Project Dependencies Using Dotnet
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore './functionsapp/Eventgridfuntionapp.csproj'  # Herstelt de afhankelijkheden van het juiste projectbestand
          dotnet build './functionsapp/Eventgridfuntionapp.csproj' --configuration Release --output ./output  # Bouw het project
          popd
      
      # Stap 5: Login naar Azure met behulp van de Azure-login actie
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Stap 6: Deploy naar Azure Function App
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'paymentsystemfunction'  # De naam van je Azure Function App
          slot-name: 'Production'           # De slotnaam (bijv. Production)
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'  # Het pad naar de outputmap na de build
